### ISSUE TITLE
error in install with composer

### ISSUE THREAD

**Issue by asadghazanfary** [edenreich/PHP-Upload-Class#8]
hello @edenreich when i use this command **composer require reich/upload** for install package with composer i get this error.

![capture](https://user-images.githubusercontent.com/5650939/42396989-60c6ddca-8179-11e8-8c17-29f2b9b7ed2a.PNG)

how can fix it?

thank's

**Comment by edenreich** [comment]
Hi @asadghazanfary,

first try to clear composer cache:
```composer clearcache```

for me it works just fine..
![test](https://user-images.githubusercontent.com/16985712/42725518-08ebc874-8785-11e8-9fe4-270a4e88515d.jpg)

some other people had the same issue, please refer to composer issue:
https://github.com/composer/composer/issues/4388

It might has to do with firewall rules. when you try to install other packages from composer registry it works ?

**Comment by asadghazanfary** [comment]
thank you @edenreich 

It works for me

**Comment by edenreich** [comment]
great :)
